spring:
    datasource:
        #schema: classpath*:scripts/schema.sql
        #continue-on-error: false
        #sql-script-encoding: utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://39.108.184.215/db_mblog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: mblog
        password: mblog_123
#        url: jdbc:mysql://10.128.208.160/db_mblog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
#        username: root
#        password: tclonline
    flyway:
        enabled: true
    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.scripts.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ${site.location}/storage/indexes